export const LEVELS = {
  A1: {
    id: 'a1',
    name: 'Beginner',
    label: 'A1',
    cards: [
      { id: 'a1_1', imageId: 'a1_1', type: 'text', value: 'House', flipped: false, matched: false },
      { id: 'a1_1i', imageId: 'a1_1', type: 'image', value: '🏠', flipped: false, matched: false },
      { id: 'a1_2', imageId: 'a1_2', type: 'text', value: 'Dog', flipped: false, matched: false },
      { id: 'a1_2i', imageId: 'a1_2', type: 'image', value: '🐕', flipped: false, matched: false },
      { id: 'a1_3', imageId: 'a1_3', type: 'text', value: 'Cat', flipped: false, matched: false },
      { id: 'a1_3i', imageId: 'a1_3', type: 'image', value: '🐱', flipped: false, matched: false },
      { id: 'a1_4', imageId: 'a1_4', type: 'text', value: 'Apple', flipped: false, matched: false },
      { id: 'a1_4i', imageId: 'a1_4', type: 'image', value: '🍎', flipped: false, matched: false },
      { id: 'a1_5', imageId: 'a1_5', type: 'text', value: 'Book', flipped: false, matched: false },
      { id: 'a1_5i', imageId: 'a1_5', type: 'image', value: '📚', flipped: false, matched: false },
      { id: 'a1_6', imageId: 'a1_6', type: 'text', value: 'Sun', flipped: false, matched: false },
      { id: 'a1_6i', imageId: 'a1_6', type: 'image', value: '☀️', flipped: false, matched: false },
      { id: 'a1_7', imageId: 'a1_7', type: 'text', value: 'Moon', flipped: false, matched: false },
      { id: 'a1_7i', imageId: 'a1_7', type: 'image', value: '🌙', flipped: false, matched: false },
      { id: 'a1_8', imageId: 'a1_8', type: 'text', value: 'Star', flipped: false, matched: false },
      { id: 'a1_8i', imageId: 'a1_8', type: 'image', value: '⭐', flipped: false, matched: false },
      { id: 'a1_9', imageId: 'a1_9', type: 'text', value: 'Car', flipped: false, matched: false },
      { id: 'a1_9i', imageId: 'a1_9', type: 'image', value: '🚗', flipped: false, matched: false },
      { id: 'a1_10', imageId: 'a1_10', type: 'text', value: 'Ball', flipped: false, matched: false },
      { id: 'a1_10i', imageId: 'a1_10', type: 'image', value: '⚽', flipped: false, matched: false },
      { id: 'a1_11', imageId: 'a1_11', type: 'text', value: 'Tree', flipped: false, matched: false },
      { id: 'a1_11i', imageId: 'a1_11', type: 'image', value: '🌳', flipped: false, matched: false },
      { id: 'a1_12', imageId: 'a1_12', type: 'text', value: 'Fish', flipped: false, matched: false },
      { id: 'a1_12i', imageId: 'a1_12', type: 'image', value: '🐟', flipped: false, matched: false },
      { id: 'a1_13', imageId: 'a1_13', type: 'text', value: 'Bird', flipped: false, matched: false },
      { id: 'a1_13i', imageId: 'a1_13', type: 'image', value: '🐦', flipped: false, matched: false },
      { id: 'a1_14', imageId: 'a1_14', type: 'text', value: 'Water', flipped: false, matched: false },
      { id: 'a1_14i', imageId: 'a1_14', type: 'image', value: '💧', flipped: false, matched: false },
      { id: 'a1_15', imageId: 'a1_15', type: 'text', value: 'Phone', flipped: false, matched: false },
      { id: 'a1_15i', imageId: 'a1_15', type: 'image', value: '📱', flipped: false, matched: false },
      { id: 'a1_16', imageId: 'a1_16', type: 'text', value: 'Heart', flipped: false, matched: false },
      { id: 'a1_16i', imageId: 'a1_16', type: 'image', value: '❤️', flipped: false, matched: false },
      { id: 'a1_17', imageId: 'a1_17', type: 'text', value: 'Clock', flipped: false, matched: false },
      { id: 'a1_17i', imageId: 'a1_17', type: 'image', value: '🕐', flipped: false, matched: false },
      { id: 'a1_18', imageId: 'a1_18', type: 'text', value: 'Flower', flipped: false, matched: false },
      { id: 'a1_18i', imageId: 'a1_18', type: 'image', value: '🌸', flipped: false, matched: false },
      { id: 'a1_19', imageId: 'a1_19', type: 'text', value: 'Hand', flipped: false, matched: false },
      { id: 'a1_19i', imageId: 'a1_19', type: 'image', value: '👋', flipped: false, matched: false },
      { id: 'a1_20', imageId: 'a1_20', type: 'text', value: 'Eyes', flipped: false, matched: false },
      { id: 'a1_20i', imageId: 'a1_20', type: 'image', value: '👀', flipped: false, matched: false },
    ]
  },
  A2: {
    id: 'a2',
    name: 'Elementary',
    label: 'A2',
    cards: [
      { id: 'a2_1', imageId: 'a2_1', type: 'text', value: 'Running', flipped: false, matched: false },
      { id: 'a2_1i', imageId: 'a2_1', type: 'image', value: '🏃', flipped: false, matched: false },
      { id: 'a2_2', imageId: 'a2_2', type: 'text', value: 'Swimming', flipped: false, matched: false },
      { id: 'a2_2i', imageId: 'a2_2', type: 'image', value: '🏊', flipped: false, matched: false },
      { id: 'a2_3', imageId: 'a2_3', type: 'text', value: 'Cooking', flipped: false, matched: false },
      { id: 'a2_3i', imageId: 'a2_3', type: 'image', value: '👩‍🍳', flipped: false, matched: false },
      { id: 'a2_4', imageId: 'a2_4', type: 'text', value: 'Reading', flipped: false, matched: false },
      { id: 'a2_4i', imageId: 'a2_4', type: 'image', value: '📖', flipped: false, matched: false },
      { id: 'a2_5', imageId: 'a2_5', type: 'text', value: 'Shopping', flipped: false, matched: false },
      { id: 'a2_5i', imageId: 'a2_5', type: 'image', value: '🛍️', flipped: false, matched: false },
      { id: 'a2_6', imageId: 'a2_6', type: 'text', value: 'Driving', flipped: false, matched: false },
      { id: 'a2_6i', imageId: 'a2_6', type: 'image', value: '🚗', flipped: false, matched: false },
      { id: 'a2_7', imageId: 'a2_7', type: 'text', value: 'Dancing', flipped: false, matched: false },
      { id: 'a2_7i', imageId: 'a2_7', type: 'image', value: '💃', flipped: false, matched: false },
      { id: 'a2_8', imageId: 'a2_8', type: 'text', value: 'Singing', flipped: false, matched: false },
      { id: 'a2_8i', imageId: 'a2_8', type: 'image', value: '🎤', flipped: false, matched: false },
      { id: 'a2_9', imageId: 'a2_9', type: 'text', value: 'Writing', flipped: false, matched: false },
      { id: 'a2_9i', imageId: 'a2_9', type: 'image', value: '✍️', flipped: false, matched: false },
      { id: 'a2_10', imageId: 'a2_10', type: 'text', value: 'Eating', flipped: false, matched: false },
      { id: 'a2_10i', imageId: 'a2_10', type: 'image', value: '🍽️', flipped: false, matched: false },
      { id: 'a2_11', imageId: 'a2_11', type: 'text', value: 'Sleeping', flipped: false, matched: false },
      { id: 'a2_11i', imageId: 'a2_11', type: 'image', value: '😴', flipped: false, matched: false },
      { id: 'a2_12', imageId: 'a2_12', type: 'text', value: 'Working', flipped: false, matched: false },
      { id: 'a2_12i', imageId: 'a2_12', type: 'image', value: '💼', flipped: false, matched: false },
      { id: 'a2_13', imageId: 'a2_13', type: 'text', value: 'Playing', flipped: false, matched: false },
      { id: 'a2_13i', imageId: 'a2_13', type: 'image', value: '🎮', flipped: false, matched: false },
      { id: 'a2_14', imageId: 'a2_14', type: 'text', value: 'Painting', flipped: false, matched: false },
      { id: 'a2_14i', imageId: 'a2_14', type: 'image', value: '🎨', flipped: false, matched: false },
      { id: 'a2_15', imageId: 'a2_15', type: 'text', value: 'Cleaning', flipped: false, matched: false },
      { id: 'a2_15i', imageId: 'a2_15', type: 'image', value: '🧹', flipped: false, matched: false },
      { id: 'a2_16', imageId: 'a2_16', type: 'text', value: 'Walking', flipped: false, matched: false },
      { id: 'a2_16i', imageId: 'a2_16', type: 'image', value: '🚶', flipped: false, matched: false },
      { id: 'a2_17', imageId: 'a2_17', type: 'text', value: 'Cycling', flipped: false, matched: false },
      { id: 'a2_17i', imageId: 'a2_17', type: 'image', value: '🚲', flipped: false, matched: false },
      { id: 'a2_18', imageId: 'a2_18', type: 'text', value: 'Talking', flipped: false, matched: false },
      { id: 'a2_18i', imageId: 'a2_18', type: 'image', value: '💬', flipped: false, matched: false },
      { id: 'a2_19', imageId: 'a2_19', type: 'text', value: 'Listening', flipped: false, matched: false },
      { id: 'a2_19i', imageId: 'a2_19', type: 'image', value: '👂', flipped: false, matched: false },
      { id: 'a2_20', imageId: 'a2_20', type: 'text', value: 'Smiling', flipped: false, matched: false },
      { id: 'a2_20i', imageId: 'a2_20', type: 'image', value: '😊', flipped: false, matched: false },
    ]
  },
  B1: {
    id: 'b1',
    name: 'Intermediate',
    label: 'B1',
    cards: [
      { id: 'b1_1', imageId: 'b1_1', type: 'text', value: 'Achievement', flipped: false, matched: false },
      { id: 'b1_1i', imageId: 'b1_1', type: 'image', value: '🏆', flipped: false, matched: false },
      { id: 'b1_2', imageId: 'b1_2', type: 'text', value: 'Innovation', flipped: false, matched: false },
      { id: 'b1_2i', imageId: 'b1_2', type: 'image', value: '💡', flipped: false, matched: false },
      { id: 'b1_3', imageId: 'b1_3', type: 'text', value: 'Sustainability', flipped: false, matched: false },
      { id: 'b1_3i', imageId: 'b1_3', type: 'image', value: '🌱', flipped: false, matched: false },
      { id: 'b1_4', imageId: 'b1_4', type: 'text', value: 'Technology', flipped: false, matched: false },
      { id: 'b1_4i', imageId: 'b1_4', type: 'image', value: '💻', flipped: false, matched: false },
      { id: 'b1_5', imageId: 'b1_5', type: 'text', value: 'Communication', flipped: false, matched: false },
      { id: 'b1_5i', imageId: 'b1_5', type: 'image', value: '📱', flipped: false, matched: false },
      { id: 'b1_6', imageId: 'b1_6', type: 'text', value: 'Creativity', flipped: false, matched: false },
      { id: 'b1_6i', imageId: 'b1_6', type: 'image', value: '🎨', flipped: false, matched: false },
      { id: 'b1_7', imageId: 'b1_7', type: 'text', value: 'Leadership', flipped: false, matched: false },
      { id: 'b1_7i', imageId: 'b1_7', type: 'image', value: '👑', flipped: false, matched: false },
      { id: 'b1_8', imageId: 'b1_8', type: 'text', value: 'Networking', flipped: false, matched: false },
      { id: 'b1_8i', imageId: 'b1_8', type: 'image', value: '🤝', flipped: false, matched: false },
      { id: 'b1_9', imageId: 'b1_9', type: 'text', value: 'Collaboration', flipped: false, matched: false },
      { id: 'b1_9i', imageId: 'b1_9', type: 'image', value: '🤲', flipped: false, matched: false },
      { id: 'b1_10', imageId: 'b1_10', type: 'text', value: 'Environment', flipped: false, matched: false },
      { id: 'b1_10i', imageId: 'b1_10', type: 'image', value: '🌍', flipped: false, matched: false },
      { id: 'b1_11', imageId: 'b1_11', type: 'text', value: 'Development', flipped: false, matched: false },
      { id: 'b1_11i', imageId: 'b1_11', type: 'image', value: '📈', flipped: false, matched: false },
      { id: 'b1_12', imageId: 'b1_12', type: 'text', value: 'Investment', flipped: false, matched: false },
      { id: 'b1_12i', imageId: 'b1_12', type: 'image', value: '💰', flipped: false, matched: false },
      { id: 'b1_13', imageId: 'b1_13', type: 'text', value: 'Strategy', flipped: false, matched: false },
      { id: 'b1_13i', imageId: 'b1_13', type: 'image', value: '♟️', flipped: false, matched: false },
      { id: 'b1_14', imageId: 'b1_14', type: 'text', value: 'Research', flipped: false, matched: false },
      { id: 'b1_14i', imageId: 'b1_14', type: 'image', value: '🔬', flipped: false, matched: false },
      { id: 'b1_15', imageId: 'b1_15', type: 'text', value: 'Education', flipped: false, matched: false },
      { id: 'b1_15i', imageId: 'b1_15', type: 'image', value: '🎓', flipped: false, matched: false },
      { id: 'b1_16', imageId: 'b1_16', type: 'text', value: 'Diversity', flipped: false, matched: false },
      { id: 'b1_16i', imageId: 'b1_16', type: 'image', value: '🌈', flipped: false, matched: false },
      { id: 'b1_17', imageId: 'b1_17', type: 'text', value: 'Motivation', flipped: false, matched: false },
      { id: 'b1_17i', imageId: 'b1_17', type: 'image', value: '🎯', flipped: false, matched: false },
      { id: 'b1_18', imageId: 'b1_18', type: 'text', value: 'Experience', flipped: false, matched: false },
      { id: 'b1_18i', imageId: 'b1_18', type: 'image', value: '⭐', flipped: false, matched: false },
      { id: 'b1_19', imageId: 'b1_19', type: 'text', value: 'Opportunity', flipped: false, matched: false },
      { id: 'b1_19i', imageId: 'b1_19', type: 'image', value: '🚪', flipped: false, matched: false },
      { id: 'b1_20', imageId: 'b1_20', type: 'text', value: 'Efficiency', flipped: false, matched: false },
      { id: 'b1_20i', imageId: 'b1_20', type: 'image', value: '⚡', flipped: false, matched: false },
    ]
  }
}; 