export const COURSES = [
  // Existing 20 courses
  {
    id: 21,
    title: "English for Travel",
    description: "Learn essential phrases for traveling abroad",
    instructor: "Alice Cooper",
    price: 29.99,
    rating: 4.6,
    level: "Beginner",
    duration: "4 weeks",
    subject: "Speaking",
    thumbnail: "/placeholder.svg",
    icon: "Brain",
  },
  {
    id: 22,
    title: "Advanced Business Communication",
    description: "Enhance your professional communication skills",
    instructor: "Mark Evans",
    price: 59.99,
    rating: 4.9,
    level: "Advanced",
    duration: "8 weeks",
    subject: "Business",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 23,
    title: "Everyday Idioms",
    description: "Master common idioms for daily conversations",
    instructor: "Nina Patel",
    price: 34.99,
    rating: 4.7,
    level: "Intermediate",
    duration: "5 weeks",
    subject: "Vocabulary",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 24,
    title: "Creative Storytelling",
    description: "Learn to craft compelling stories",
    instructor: "Oliver Scott",
    price: 44.99,
    rating: 4.8,
    level: "Intermediate",
    duration: "6 weeks",
    subject: "Writing",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 25,
    title: "Public Speaking Mastery",
    description: "Become a confident public speaker",
    instructor: "Sophia Adams",
    price: 59.99,
    rating: 4.9,
    level: "Advanced",
    duration: "8 weeks",
    subject: "Speaking",
    thumbnail: "/placeholder.svg",
    icon: "Brain",
  },
  {
    id: 26,
    title: "Grammar for Professionals",
    description: "Polish your grammar for professional settings",
    instructor: "James Carter",
    price: 49.99,
    rating: 4.8,
    level: "Advanced",
    duration: "7 weeks",
    subject: "Grammar",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 27,
    title: "Cultural Etiquette",
    description: "Learn proper etiquette across cultures",
    instructor: "Emma Watson",
    price: 34.99,
    rating: 4.6,
    level: "Intermediate",
    duration: "5 weeks",
    subject: "Culture",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 28,
    title: "Business Negotiations",
    description: "Master negotiation skills for business",
    instructor: "David Parker",
    price: 59.99,
    rating: 4.9,
    level: "Advanced",
    duration: "8 weeks",
    subject: "Business",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 29,
    title: "Listening for Details",
    description: "Improve your ability to catch details in conversations",
    instructor: "Olivia Brown",
    price: 29.99,
    rating: 4.7,
    level: "Beginner",
    duration: "4 weeks",
    subject: "Speaking",
    thumbnail: "/placeholder.svg",
    icon: "Brain",
  },
  {
    id: 30,
    title: "Essay Writing Advanced",
    description: "Refine your essay writing skills",
    instructor: "Liam Green",
    price: 49.99,
    rating: 4.8,
    level: "Advanced",
    duration: "8 weeks",
    subject: "Writing",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 31,
    title: "Pronunciation for Professionals",
    description: "Enhance your pronunciation for professional settings",
    instructor: "Sophia White",
    price: 44.99,
    rating: 4.7,
    level: "Intermediate",
    duration: "6 weeks",
    subject: "Speaking",
    thumbnail: "/placeholder.svg",
    icon: "Brain",
  },
  {
    id: 32,
    title: "Cultural Awareness",
    description: "Understand cultural differences in depth",
    instructor: "Chris Taylor",
    price: 34.99,
    rating: 4.6,
    level: "Intermediate",
    duration: "5 weeks",
    subject: "Culture",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 33,
    title: "Advanced Writing Techniques",
    description: "Learn advanced techniques for effective writing",
    instructor: "Laura Harris",
    price: 54.99,
    rating: 4.9,
    level: "Advanced",
    duration: "7 weeks",
    subject: "Writing",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 34,
    title: "Conversational English for Beginners",
    description: "Start speaking English confidently",
    instructor: "Tom Wilson",
    price: 29.99,
    rating: 4.6,
    level: "Beginner",
    duration: "4 weeks",
    subject: "Speaking",
    thumbnail: "/placeholder.svg",
    icon: "Brain",
  },
  {
    id: 35,
    title: "Business Email Writing",
    description: "Write effective business emails",
    instructor: "Sophia Martinez",
    price: 39.99,
    rating: 4.7,
    level: "Intermediate",
    duration: "6 weeks",
    subject: "Business",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 36,
    title: "Advanced Pronunciation",
    description: "Perfect your pronunciation for advanced fluency",
    instructor: "James Lee",
    price: 44.99,
    rating: 4.8,
    level: "Advanced",
    duration: "7 weeks",
    subject: "Speaking",
    thumbnail: "/placeholder.svg",
    icon: "Brain",
  },
  {
    id: 37,
    title: "Cultural Traditions",
    description: "Explore unique traditions from around the world",
    instructor: "Emma Wilson",
    price: 34.99,
    rating: 4.6,
    level: "Intermediate",
    duration: "5 weeks",
    subject: "Culture",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 38,
    title: "Professional Writing Skills",
    description: "Develop skills for professional writing",
    instructor: "David Brown",
    price: 49.99,
    rating: 4.9,
    level: "Advanced",
    duration: "8 weeks",
    subject: "Writing",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 39,
    title: "Listening for Fluency",
    description: "Improve listening skills for fluent conversations",
    instructor: "Olivia Taylor",
    price: 29.99,
    rating: 4.7,
    level: "Beginner",
    duration: "4 weeks",
    subject: "Speaking",
    thumbnail: "/placeholder.svg",
    icon: "Brain",
  },
  {
    id: 40,
    title: "Essay Writing Essentials",
    description: "Learn the basics of essay writing",
    instructor: "Liam Johnson",
    price: 39.99,
    rating: 4.8,
    level: "Intermediate",
    duration: "6 weeks",
    subject: "Writing",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 41,
    title: "Grammar for Beginners",
    description: "Start your grammar journey",
    instructor: "Sarah Johnson",
    price: 29.99,
    rating: 4.7,
    level: "Beginner",
    duration: "4 weeks",
    subject: "Grammar",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 42,
    title: "Cultural Festivals",
    description: "Learn about festivals from different cultures",
    instructor: "Michael Chen",
    price: 34.99,
    rating: 4.6,
    level: "Intermediate",
    duration: "5 weeks",
    subject: "Culture",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 43,
    title: "Business English Essentials",
    description: "Learn the basics of business communication",
    instructor: "Elena Rodriguez",
    price: 39.99,
    rating: 4.8,
    level: "Beginner",
    duration: "6 weeks",
    subject: "Business",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 44,
    title: "Advanced Listening Practice",
    description: "Practice listening for advanced fluency",
    instructor: "David Wilson",
    price: 54.99,
    rating: 4.9,
    level: "Advanced",
    duration: "7 weeks",
    subject: "Speaking",
    thumbnail: "/placeholder.svg",
    icon: "Brain",
  },
  {
    id: 45,
    title: "Creative Writing for Beginners",
    description: "Start your creative writing journey",
    instructor: "Sophia Lee",
    price: 29.99,
    rating: 4.7,
    level: "Beginner",
    duration: "4 weeks",
    subject: "Writing",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 46,
    title: "Vocabulary for Professionals",
    description: "Expand your vocabulary for professional use",
    instructor: "James Thompson",
    price: 44.99,
    rating: 4.8,
    level: "Advanced",
    duration: "7 weeks",
    subject: "Vocabulary",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 47,
    title: "Cultural Communication",
    description: "Learn effective communication across cultures",
    instructor: "Maria Garcia",
    price: 34.99,
    rating: 4.6,
    level: "Intermediate",
    duration: "5 weeks",
    subject: "Culture",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 48,
    title: "Business Presentation Skills",
    description: "Master the art of business presentations",
    instructor: "Robert Kim",
    price: 59.99,
    rating: 4.9,
    level: "Advanced",
    duration: "8 weeks",
    subject: "Business",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
  {
    id: 49,
    title: "Listening for Beginners",
    description: "Improve your listening skills from scratch",
    instructor: "Anna Brown",
    price: 29.99,
    rating: 4.7,
    level: "Beginner",
    duration: "4 weeks",
    subject: "Speaking",
    thumbnail: "/placeholder.svg",
    icon: "Brain",
  },
  {
    id: 50,
    title: "Advanced Essay Writing",
    description: "Master advanced techniques for essay writing",
    instructor: "Chris Green",
    price: 54.99,
    rating: 4.9,
    level: "Advanced",
    duration: "8 weeks",
    subject: "Writing",
    thumbnail: "/placeholder.svg",
    icon: "BookOpen",
  },
];

export const SUBJECTS = [
  "Speaking",
  "Grammar",
  "Culture",
  "Business",
  "Vocabulary",
  "Writing",
];
export const LEVELS = ["Beginner", "Intermediate", "Advanced"];
export const DURATIONS = [
  "4 weeks",
  "5 weeks",
  "6 weeks",
  "7 weeks",
  "8 weeks",
];
